[env:controller_upload]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM6
upload_speed = 460800
monitor_speed = 460800
build_src_filter = +<main.cpp>

[env:satellite_upload]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM6
upload_speed = 460800
monitor_speed = 460800
build_src_filter = +<satellite_main.cpp>
lib_deps = robtillaart/SHT85
